name: Run FIT Testing

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
    inputs:
      fit_cli_preset:
        description: FIT preset to run.
        required: false
        type: string
        default: op-multi-lite
      fit_cli_channel:
        description: fit-cli install channel ("latest" or "ci").
        required: false
        type: string
        default: ci
      performer_image:
        description: Performer image to use (e.g. main, 1.0.2, etc.)
        required: false
        type: string
        default: main
  workflow_call:
    inputs:
      fit_cli_preset:
        required: false
        type: string
      performer_image:
        required: false
        type: string


permissions:
  id-token: write

jobs:
  run-rust-fit:
    uses: couchbaselabs/fit-cli/.github/workflows/fit-cli.yaml@main
    with:
      preset: ${{ inputs.fit_cli_preset || vars.FIT_CLI_PRESET || 'op-multi-lite' }}
      channel: ${{ inputs.fit_cli_channel || vars.FIT_CLI_CHANNEL || 'ci' }}
      performer: rust-fit-performer:${{ inputs.performer_image || 'main' }}
